### ISSUE TITLE
Add a "swingify" effect

### ISSUE THREAD

**Issue by dhsavell** [beat-machine/beat-machine#14]
This could be interesting. This entails expanding/contracting every nth beat by a fixed factor.

**Comment by JousterL** [comment]
Might look at https://github.com/Curly-Mo/swingify/blob/master/swingify.py for an example. They use librosa rather than madmom but the operations on beat objects should be identical.

**Comment by dhsavell** [comment]
I'll probably go about this with just a time stretching effect, since that can be applied on a period of every 2 beats to add swing. I'm also thinking about bundling some presets in the next minor release, so "swingify" could be one of those.
