### ISSUE TITLE
Reverse the order of each beat

### ISSUE THREAD

**Issue by justingolden21** [beat-machine/beat-machine#39]
Absolutely love this project.

I would be down to contribute if possible, although I'm not quite sure how to get it up and running on my machine.

Just a suggestion for a new feature: reverse the order of each beat. So beat 20, then beat 19, then beat 18, etc, as opposed to what's currently offered in reversing every beat such that it's beat 1 backwards then beat 2 backwards etc.

Thanks for listening to my input : )

**Comment by dhsavell** [comment]
Thanks for your suggestion! I'm only able to work on this project intermittently, but this should be simple to implement when I do get the chance. I'm also hoping to update the docs so it's clearer how to play around with the code.

**Comment by justingolden21** [comment]
Awesome! Thank you for getting back to me. I'd be happy to implement it myself after you update the docs. It's probably a me thing though, I'm just bad at figuring out how other peoples' projects are organized.

Take your time on the docs, no rush : )

**Comment by dhsavell** [comment]
Available in 3.2.0 thanks to the linked PR!

**Comment by justingolden21** [comment]
Awesome! Thank you @JousterL for adding this and @dhsavell for adding the PR!

( `beat_list.reverse()` haha gotta love Python 😃 )
