### ISSUE TITLE
Investigate better offset behavior

### ISSUE THREAD

**Issue by branchpanic** [beat-machine/beat-machine#44]
While working on a response to https://github.com/beat-machine/beat-webapp/issues/38, I realized the designed `offset` behavior for periodic effects is a bit confusing.

Because periodic effects don't apply until the index is at least equal to the offset, it's difficult to propagate complex effects all the way to the start of the song. In the issue above, I couldn't reproduce the desired result without skipping the first few beats.

Maybe some kind of "start at offset" flag (but worded better) could provide a toggle for this behavior.

**Comment by JustACuteGirlLookingForAManToFixHerBugs** [comment]
Negative offset!
