### ISSUE TITLE
Include presets

### ISSUE THREAD

**Issue by branchpanic** [beat-machine/beat-machine#46]
Include presets for common operations like remove every other beat, swap beats 2 and 4, etc. so users don't have to write them out as JSON.

**Comment by JustACuteGirlLookingForAManToFixHerBugs** [comment]
Is there a functional difference between the web version and... this one?

**Comment by branchpanic** [comment]
This repo has the Python library that powers the website. It can be used either from the command-line or Python code. The webapp repository is just the website.

**Comment by branchpanic** [comment]
[Examples](https://github.com/beat-machine/beat-machine/tree/main/examples) will have to do for now.
