### ISSUE TITLE
Idea: Pitch effects

### ISSUE THREAD

**Issue by AzamMujahidProductions** [beat-machine/beat-machine#48]
Can you please add pitch options for the Beat Machine? Like there's been some on YouTube like but it's only C note, etc.

**Comment by branchpanic** [comment]
Thanks for the suggestion. I admittedly haven't been working on beat machine much, but would love to have some features that mess with pitch.

**Comment by branchpanic** [comment]
For sure. This is relatively low-priority in comparison to #44, #41, etc. It's possible for (Python library) end users to create custom effects that do this in the meantime.

**Comment by branchpanic** [comment]
Closing this as part of cleanup/narrowing scope. Not to say it won't ever happen, just not in the immediate.
