### ISSUE TITLE
error 422

### ISSUE THREAD

**Issue by ATandem** [beat-machine/beat-machine#59]
I keep getting error 422 on this program, on iPhone, Macbook, and Mac computer. I've used yt videos and mp3s, different songs, all in one location though.

**Comment by branchpanic** [comment]
Thanks for reporting. Please follow progress on the webapp repository here: https://github.com/beat-machine/beat-webapp/issues/36.

Some fixes were just pushed to the web version. Try again and comment there if you have issues.
