### ISSUE TITLE
Are you kidding me again? -_-

### ISSUE THREAD

**Issue by juanroman74454811** [beat-machine/beat-machine#61]
![Screenshot 2022-10-17 at 10-38-56 The Beat Machine](https://user-images.githubusercontent.com/92176733/196192027-606084d1-c23b-4b41-811b-cf6203ec3be0.png)
Again,

**Comment by branchpanic** [comment]
Moving NetworkError issues to a dedicated thread, follow there: https://github.com/beat-machine/beat-webapp/issues/43
